### ISSUE TITLE
BASIC.AUTOCOMPLETE 사용 시, java.lang.ArrayIndexOutOfBoundsException 오류가 발생합니다.

### ISSUE THREAD

**Issue by ybg0416** [fastcat-co/fastcatsearch#41]
java.lang.ArrayIndexOutOfBoundsException: 16
	at org.fastcatsearch.ir.analysis.AutocompleteTokenizer.incrementToken(AutocompleteTokenizer.java:61) ~[fastcatsearch-core-2.34.2.jar:na]
	at org.apache.lucene.analysis.standard.StandardFilter.incrementToken(StandardFilter.java:36) ~[fastcatsearch-core-2.34.2.jar:na]
	at org.fastcatsearch.job.management.GetCollectionAnalyzedIndexDataJob.add(GetCollectionAnalyzedIndexDataJob.java:250) ~[fastcatsearch-server-2.34.2.jar:na]
	at org.fastcatsearch.job.management.GetCollectionAnalyzedIndexDataJob.doRun(GetCollectionAnalyzedIndexDataJob.java:169) ~[fastcatsearch-server-2.34.2.jar:na]
	at org.fastcatsearch.job.Job.run(Job.java:136) [fastcatsearch-server-2.34.2.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.8.0_73]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.8.0_73]
	at java.lang.Thread.run(Unknown Source) [na:1.8.0_73]

Oracle 문자 셋은 다음과 같습니다.

NLS_NCHAR_CONV_EXCP	FALSE
NLS_NUMERIC_CHARACTERS	.,
NLS_NCHAR_CHARACTERSET	AL32UTF8
NLS_CHARACTERSET	AL32UTF8

테스트 환경은 다음과 같습니다.
Windows 7 sp1
java version "1.8.0_73"
Java(TM) SE Runtime Environment (build 1.8.0_73-b02)
Java HotSpot(TM) 64-Bit Server VM (build 25.73-b02, mixed mode)
설정 메모리 512m

-같은 PC에서 다른 자바 버전으로 테스트
Windows 7 sp1
java version "1.6.0_23"
Java(TM) SE Runtime Environment (build 1.6.0_23-b05)
Java HotSpot(TM) Client VM (build 19.0-b09, mixed mode, sharing)
설정 메모리 512m

-서버 PC 테스트
Windows 2012 R2 Standard
java version "1.8.0_73"
Java(TM) SE Runtime Environment (build 1.8.0_73-b02)
Java HotSpot(TM) 64-Bit Server VM (build 25.73-b02, mixed mode)
설정 메모리 12g

DB에서 BASIC.AUTOCOMPLETE를 사용하여 도서명 자동 완성을 진행하고자 하였으나, 특정 데이터에서 오류가 발생합니다. 매번 해당 데이터에서 오류가 발생하여, 해당 데이터의 특수 문자 문제일까 싶어, 해당 문자를 정규식을 통해 제거하고 진행해도 다른 데이터에서 지속적으로 에러가 발생하네요. 

일단, BASIC.AUTOCOMPLETE를 제외한 STANDARD, NGRAM을 사용 했을 때는 문제 없이 정상적으로 작동했습니다.

자바 버전에 따른 차이일까 싶어 버전을 낮추고, 32bit 버전으로 사용해도 동일한 오류가 발생했습니다. 
혹시 몰라, Datasource를 INDEX_CLONE로 사용하여 테스트도 해봤는데.. 역시... ㅠㅠ

fastcatsearch-console에 있는 테스트 툴로 테스트 할 때, 첫 시도에는 에러가 나고, 이후에는 정상적으로  작동합니다

해당 문제의 재현을 위해 해당 상황을 재현한 fastcat을 압축하여 첨부합니다. 
각 컬렉션인 testdata는 데이터 일부 (1만건)을, test는 testdata를 source로 사용하여 색인을 진행하도록 되어 있습니다. 

https://drive.google.com/open?id=0B3pUG7XFahOMeTE4Mm9zeUctblE

**Comment by freshbread** [comment]
BASIC.AUTOCOMPLETE 분석기는 Index Analyzer에만 사용하시고 Query Analyzer에는 BASIC.STANDARD로 맞추신 뒤 사용해 보시기 바랍니다.

**Comment by ybg0416** [comment]
![image](https://cloud.githubusercontent.com/assets/11923112/14638182/143cf3de-0671-11e6-90a5-56d0f82c13a3.png)
아하.. 말씀 주신대로 진행했더니 정상 작동하는 것을 확인했습니다. 
쿼리를 던질 때 분리되야 한다는 생각에 미처 시도조차 안해봤네요.. ㅠㅠ
도움 주셔서 진심으로 감사합니다 ㅠㅠ

여쭤볼게 있는데, 혹시 ht옵션을 적용해도, 
결과물에 추가되지 않는 문제는 어떤 이유인지 알 수 있을까요? 
![image](https://cloud.githubusercontent.com/assets/11923112/14638446/6639bd4c-0672-11e6-9dd6-7646646f10d2.png)

**Comment by freshbread** [comment]
하이라이팅을 사용하시려면 se 파라미터에 옵션 값에 4를 더해주셔야 합니다. 옵션 값을 입력하지 않으신 상태여서 기본 값이 3(유사어확장 + 금지어적용)이 적용되기 때문에 현재 사용하시는 검색 쿼리에는 하이라이팅이 되지 않는 상태입니다. 한글어 분석기를 사용하시지 않으시니 옵션 1, 옵션 2 값은 적용하셔도 별로 의미가 없습니다.

se={필드명:키워드:가중치:옵션}와 같은 식으로 넣어주셔야 합니다.
스코어로 정렬하시지는 않으시니 가중치는 -1로 넣어 주시거나 정수 값을 적당히 넣어주시고, 최소한 옵션 값을 4 또는 그 이상의 값으로 주시면 됩니다.
se=T_245_A_TITLE:검색어:-1:4
분석기 라이선스를 구입하지 않으시고 베이직 분석기만으로 자동완성 키워드를 쓰신다면 옵션 4 이외에는 쓸 일은 없으실 겁니다.

옵션에 대해서는 매뉴얼을 참고해 주세요.
https://www.fastcat.co/document/fastcatsearch/fastcatsearch_query_ko#user-content-se

**Comment by ybg0416** [comment]
![image](https://cloud.githubusercontent.com/assets/11923112/14707205/5c28ce8c-07fe-11e6-863b-adbcfb6658df.png)

매뉴얼을 제대로 정독하지 않은 저를 반성하게 되네요....ㅠㅠ 
도움 주셔서 감사합니다.!!
